# Generated by Django 5.2.8 on 2025-12-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_subscription_plan_subscription_current_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
