# Generated by Django 5.2.8 on 2025-12-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscription_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_weekly_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weekly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
