# Generated by Django 5.2.8 on 2025-12-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_billing_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial_end',
        ),
    ]
