# Generated by Django 5.2.8 on 2025-12-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscriptioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
