# Generated by Django 5.2.8 on 2025-12-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_plan',
            field=models.CharField(choices=[('free', 'Free'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
