# Generated by Django 5.2.8 on 2025-12-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptioninvoice',
            old_name='period_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscriptioninvoice',
            old_name='period_start',
            new_name='start_date',
        ),
    ]
