# Generated by Django 5.2.8 on 2026-01-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_mobilesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileSubscription',
        ),
    ]
