# Generated by Django 5.2.8 on 2025-11-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journey', '0003_alter_journey_icon_journey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
                ('devotion', models.TextField(max_length=255)),
                ('reflection', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prayer', models.TextField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='prayers/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
            ],
        ),
        migrations.CreateModel(
            name='MicroAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
            ],
        ),
    ]
