# Generated by Django 5.2.8 on 2025-11-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprayer',
            name='name',
        ),
    ]
