# Generated by Django 5.2.8 on 2025-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0002_remove_dailyprayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='devotion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailydevotion',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='dailydevotion',
            name='reflection',
            field=models.CharField(),
        ),
    ]
