# Generated by Django 5.2.8 on 2025-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0003_alter_dailydevotion_devotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='reflection',
            field=models.TextField(),
        ),
    ]
