# Generated by Django 5.2.8 on 2025-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0004_alter_dailydevotion_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microaction',
            name='action',
            field=models.CharField(),
        ),
    ]
