# Generated by Django 5.2.8 on 2025-12-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0006_reflectionspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflectionspace',
            name='user_id',
        ),
    ]
