# Generated by Django 5.2.8 on 2025-12-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0007_remove_reflectionspace_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReflectionSpace',
        ),
    ]
