# Generated by Django 5.2.8 on 2025-12-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0008_delete_reflectionspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dailydevotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_devotion.dailydevotion')),
            ],
        ),
    ]
