# Generated by Django 5.2.8 on 2025-12-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0009_reflectionspace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReflectionSpace',
            new_name='DailyReflectionSpace',
        ),
        migrations.RenameField(
            model_name='dailyreflectionspace',
            old_name='note',
            new_name='reflection_note',
        ),
    ]
