# Generated by Django 5.2.8 on 2025-12-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0010_rename_reflectionspace_dailyreflectionspace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydevotion',
            old_name='name',
            new_name='scripture_name',
        ),
    ]
