# Generated by Django 5.2.8 on 2025-12-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0011_rename_name_dailydevotion_scripture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydevotion',
            name='journey_id',
        ),
    ]
