# Generated by Django 5.2.8 on 2025-12-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0012_remove_dailydevotion_journey_id'),
        ('journey', '0004_personajourney_days_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydevotion',
            name='journey_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journey.journey'),
            preserve_default=False,
        ),
    ]
