# Generated by Django 5.2.8 on 2025-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0013_dailydevotion_journey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprayer',
            name='prayer',
            field=models.TextField(),
        ),
    ]
