# Generated by Django 5.2.8 on 2025-12-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0015_dailyreflectionspace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='scripture_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='microaction',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
