# Generated by Django 5.2.8 on 2025-12-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0016_alter_dailydevotion_scripture_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprayer',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microaction',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
