# Generated by Django 4.2.16 on 2025-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0016_alter_dailydevotion_scripture_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='devotion',
            field=models.TextField(),
        ),
    ]
