# Generated by Django 4.2.16 on 2025-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0017_alter_dailydevotion_devotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microaction',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
