# Generated by Django 5.2.8 on 2025-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0017_alter_dailyprayer_audio_alter_microaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprayer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='prayers/audio/'),
        ),
    ]
