# Generated by Django 5.2.8 on 2025-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0018_alter_dailyprayer_audio'),
        ('daily_devotion', '0018_alter_microaction_action'),
    ]

    operations = [
    ]
