# Generated by Django 5.2.8 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_devotion', '0019_merge_20251228_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microaction',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
