# Generated by Django 5.2.8 on 2025-11-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journey', '0003_alter_journey_icon_journey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.dailyquiz')),
            ],
        ),
    ]
