# Generated by Django 5.2.8 on 2025-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizansweroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
