# Generated by Django 5.2.8 on 2025-12-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizansweroption_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizansweroption',
            old_name='daily_quiz',
            new_name='daily_quiz_id',
        ),
    ]
