# Generated by Django 5.2.8 on 2025-12-22 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_daily_quiz_quizansweroption_daily_quiz_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('daily_quiz_id', 'user_id')},
        ),
    ]
