# Generated by Django 5.2.8 on 2025-11-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='journe_id',
            new_name='journey_id',
        ),
        migrations.RenameField(
            model_name='journey_icon',
            old_name='icon_url',
            new_name='icon',
        ),
    ]
