# Generated by Django 5.2.8 on 2025-11-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_rename_journe_id_days_journey_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey_icon',
            name='journey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='journey.journey'),
        ),
    ]
