# Generated by Django 5.2.8 on 2025-12-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_alter_journey_icon_journey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=255, unique=True)),
                ('sequence', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
