# Generated by Django 5.2.8 on 2025-12-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_personajourney_days_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='days',
            unique_together={('journey_id', 'order')},
        ),
    ]
