# Generated by Django 5.2.8 on 2025-12-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_days_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='details',
            field=models.TextField(),
        ),
    ]
