# Generated by Django 5.2.8 on 2025-12-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='journey_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
