# Generated by Django 5.2.8 on 2025-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_journey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
