# Generated by Django 5.2.8 on 2025-12-05 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_personajourney_days_order'),
        ('userprogress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourneyprogress',
            name='completed_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserDayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
