# Generated by Django 5.2.8 on 2025-12-05 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_days_unique_together'),
        ('userprogress', '0002_alter_userjourneyprogress_completed_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneyprogress',
            unique_together={('user', 'journey_id')},
        ),
    ]
