# Generated by Django 5.2.8 on 2025-12-05 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_days_unique_together'),
        ('userprogress', '0003_alter_userjourneyprogress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjourneyprogress',
            old_name='journey_id',
            new_name='journey',
        ),
        migrations.AlterUniqueTogether(
            name='userjourneyprogress',
            unique_together={('user', 'journey')},
        ),
    ]
