# Generated by Django 5.2.8 on 2025-12-15 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeydetails_details'),
        ('userprogress', '0004_rename_journey_id_userjourneyprogress_journey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdayprogress',
            unique_together={('user', 'day_id')},
        ),
        migrations.AddField(
            model_name='userdayprogress',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('current', 'Current'), ('completed', 'Completed')], default='locked', max_length=20),
        ),
        migrations.AddField(
            model_name='userjourneyprogress',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('current', 'Current'), ('completed', 'Completed')], default='locked', max_length=20),
        ),
        migrations.RemoveField(
            model_name='userdayprogress',
            name='completed',
        ),
    ]
