# Generated by Django 5.2.8 on 2025-12-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0005_alter_userdayprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdayprogress',
            name='created_at',
        ),
    ]
