# Generated by Django 5.2.8 on 2025-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0006_remove_userdayprogress_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdayprogress',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
