# Generated by Django 5.2.8 on 2025-12-17 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeydetails_details'),
        ('userprogress', '0007_userdayprogress_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('prayer', 'Daily Prayer'), ('devotion', 'Daily Devotion'), ('action', "Today's Action"), ('reflection', 'Reflection Space'), ('quiz', 'Daily Quiz')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day', 'item_type')},
            },
        ),
    ]
