# Generated by Django 5.2.8 on 2025-12-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0008_userdayitemprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
