# Generated by Django 5.2.8 on 2025-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0009_alter_userdayprogress_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayprogress',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
