# Generated by Django 5.2.8 on 2025-12-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeydetails_details'),
        ('userprogress', '0010_alter_userdayprogress_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='jourenystepitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('prayer', 'Daily Prayer'), ('devotion', 'Daily Devotion'), ('action', "Today's Action"), ('reflection', 'Reflection Space')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.days')),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
            ],
        ),
    ]
