# Generated by Django 5.2.8 on 2025-12-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeydetails_details'),
        ('userprogress', '0011_jourenystepitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jourenystepitem',
            unique_together={('days_id', 'step_name')},
        ),
    ]
