# Generated by Django 5.2.8 on 2025-12-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0012_alter_jourenystepitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
