# Generated by Django 5.2.8 on 2025-12-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0013_alter_userdayprogress_completed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneyprogress',
            unique_together=set(),
        ),
    ]
