# Generated by Django 5.2.8 on 2025-12-22 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeydetails_details'),
        ('userprogress', '0014_alter_userjourneyprogress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneyprogress',
            unique_together={('user', 'journey')},
        ),
    ]
